name: "Doraemon - Mittsu no Seireiseki (J)"

checksum1: 0xbff7b1c2
checksum2: 0xaebf148e

basename: "doraemon"

ranges:
   - [0x000000, 0x000040, "header", "header"]
   - [0x000040, 0x001000, "bin", "boot"]
   - [0x001000, 0x0A0754, "asm", "main", 0x80000400]
# TODO: RSP ucode
#   - [0x0A0830, 0x0A1030, "bin", "rsp.audio"]     # 0x8009FC30 [0x0800]
#   - [0x0A3040, 0x0A4040, "bin", "rsp.graphics"]  # 0x800A2440 [0x1000]

labels:
   - [0x80000400, "EntryPoint"]
   - [0x80000450, "Main"]
   - [0x80001BF8, "ReadControllerData"]
   - [0x80001C38, "InitControllers"]
   - [0x800004C0, "Thread1_Idle"]
   - [0x80006D94, "Thread3"]
   - [0x80000BC0, "Thread4"]
   - [0x80000550, "Thread10"]
   - [0x80001EF0, "Thread20"]
   - [0x800016D0, "Thread30"]
   - [0x80002470, "Thread44_1"]
   - [0x80002944, "Thread44_2"]
   - [0x80002AF4, "Thread44_3"]
   - [0x8008BAC0, "osContInit"]
   - [0x8008AF70, "osGetTime"]
   - [0x80091950, "osGetCount"]
   - [0x80092068, "__ull_div"]
   - [0x80092000, "__ull_rshift"]
   - [0x8009202C, "__ull_rem"]
   - [0x800920A4, "__ll_lshift"]
   - [0x800920D0, "__ll_rem"]
   - [0x8009210C, "__ll_div"]
   - [0x80092168, "__ll_mul"]
   - [0x80092198, "__ull_divremi"]
   - [0x800921F8, "__ll_mod"]
   - [0x80092294, "__ll_rshift"]
   - [0x8008A840, "osCreateMesgQueue"]
   - [0x80095000, "osSetTimer"]
   - [0x8008AE30, "osRecvMesg"]
   - [0x8008B040, "osSendMesg"]
   - [0x8008BD88, "__osPackRequestData"]
   - [0x80098A70, "__osSiRawStartDma"]
   - [0x8008BCB8, "__osContGetInitData"]
   - [0x800989B0, "__osSiCreateAccessQueue"]
   - [0x8008BE80, "osEepromProbe"]
   - [0x800950E0, "osEepromRead"]
   - [0x80089E50, "osEepromLongRead"]
   - [0x80094B20, "osEepromWrite"]
   - [0x80089D10, "osEepromLongWrite"]
   - [0x80094CD0, "EepromWriteSerialize"]
   - [0x80091B40, "guMtxIdentF"]
   - [0x80091CB0, "guScaleF"]
   - [0x80091D04, "guScale"]
   - [0x80091A40, "guMtxF2L"]
   - [0x8008C820, "guPerspectiveF"]
   - [0x8008CA50, "guPerspective"]
   - [0x80091D50, "guRotateRPYF"]
   - [0x80091EE4, "guRotateRPY"]
   - [0x8008C4E0, "sinf"]
   - [0x8008C6A0, "cosf"]
   - [0x80098A00, "__osSiGetAccess"]
   - [0x80094DDC, "__osEepStatus"]
   - [0x80098A44, "__osSiRelAccess"]
   - [0x80089F90, "osInitialize"]
   - [0x800953F0, "__osGetSR"]
   - [0x80095400, "__osSetFpcCsr"]
   - [0x80095410, "__osSiRawReadIo"]
   - [0x80095460, "__osSiRawWriteIo"]
   - [0x8009D8E0, "__osSiDeviceBusy"]
   - [0x800954B0, "__osExceptionPreamble"]
   - [0x800954C0, "__osExceptionHandler"]
   - [0x80091890, "osWriteBackDCache"]
   - [0x80095DB0, "osInvalCache"]
   - [0x8008DD60, "osInvalDCache"]
   - [0x8008B320, "osWriteBackDCacheAll"]
   - [0x80095E90, "osEPiRawReadIo"]
   - [0x8008DBB0, "osPiStartDma"]
   - [0x8009CF90, "osJamMesg"]
   - [0x800984C0, "memcpy"]
   - [0x800984EC, "strlen"]
   - [0x80098514, "strchr"]
   - [0x80095EF0, "bzero"]
   - [0x80098560, "bcopy"]
   - [0x8008C810, "sqrtf"]
   - [0x8008B250, "sprintf"]
   - [0x8008B274, "proutSprintf"]
   - [0x80097E70, "_Printf"]
   - [0x8008D390, "osVirtualToPhysical"]
   - [0x8008B6E0, "osContStartReadData"]
   - [0x8008B7A4, "osContGetReadData"]
   - [0x80095ACC, "__osEnqueueAndYield"]
   - [0x80095C14, "__osPopThread"]
   - [0x80095BCC, "__osEnqueueThread"]
   - [0x80095C24, "__osDispatchThread"]
   - [0x80096860, "__osDisableInt"]
   - [0x80096880, "__osRestoreInt"]
   - [0x8008A230, "osCreateThread"]
   - [0x8008A5B0, "osDestroyThread"]
   - [0x80095DA0, "__osCleanupThread"]
   - [0x8008A870, "osCreateViManager"]
   - [0x8008A9F8, "__osViDevMgrMain"]
   - [0x80096FBC, "__osTimerInterrupt"]
   - [0x8009DB00, "__osSetCompare"]
   - [0x80097134, "__osSetTimerIntr"]
   - [0x800971A8, "__osInsertTimer"]
   - [0x80096F30, "__osTimerServicesInit"]
   - [0x8008ABD0, "osViSetMode"]
   - [0x8008AC40, "osViBlack"]
   - [0x800916D0, "osViSetSpecialFeatures"]
   - [0x8008B2D0, "osViSwapBuffer"]
   - [0x8008ACB0, "osSetEventMsg"]
   - [0x8008AD20, "osViSetEventMsg"]
   - [0x800969A0, "osGetThreadPri"]
   - [0x8008A4D0, "osSetThreadPri"]
   - [0x80097330, "__osViInit"]
   - [0x8008A380, "osStartThread"]
   - [0x800968E0, "__osPiCreateAccessQueue"]
   - [0x80096930, "__osPiGetAccess"]
   - [0x80096974, "__osPiRelAccess"]
   - [0x800969C0, "osPiRawStartDma"]
   - [0x8008A6B0, "osCreatePiManager"]
   - [0x80098870, "__osSpSetStatus"]
   - [0x800977F0, "__osSpGetStatus"]
   - [0x8008B46C, "osSpTaskLoad"]
   - [0x8008B5CC, "osSpTaskStartGo"]
   - [0x80098950, "__osSpDeviceBusy"]
   - [0x8008B6C0, "osSpTaskYield"]
   - [0x8008B350, "TaskVirtualToPhysical"]
   - [0x80098880, "__osSpSetPc"]
   - [0x800988C0, "__osSpRawStartDma"]
   - [0x8008D170, "osAiSetFrequency"]
   - [0x8008D4C0, "osAiGetLength"]
   - [0x8008D410, "osAiSetNextBuffer"]
   - [0x8009A950, "__osAiDeviceBusy"]
   - [0x8009A890, "__osProbeTLB"]
