#  ROM splitter configuration file
name: "Goldeneye 007"

#  checksums from ROM header offsets 0x10 and 0x14
#  used for auto configuration detection
checksum1: 0x0414CA61
checksum2: 0x2E57B8AA

#  base filename used for outputs (please, no spaces]
basename: "ge007.e"


ranges:
   - [0x00000000, 0x000040, "header", "header"]
   - [0x00000040, 0x001000, "bin", "boot"]
   - [0x00001000, 0x01F850, "asm", "code", 0x80000400]
   - [0x0001F850, 0x031450, "bin", "Compressedrodata"]
   - [0x00031450, 0x0329F0, "asm", "rarezip", 0x70200000]
   - [0x000329F0, 0x1047F0, "asm", "codeTLB", 0x8F000000]
   
labels:
   - [0x80000400, "entry"]
   - [0x80000450, "establishrootTLB"]
   - [0x800004BC, "get_rodata_vaddr"]
   - [0x800004C8, "get_rodata_rom_start"]
   - [0x800004D4, "get_rodata_rom_end"]
   - [0x800004E0, "getRareZipASMRomstart"]
   - [0x800004EC, "getRareZipASMRomend"]
   - [0x800004F8, "jump_decompressfile"]
   - [0x80000510, "init"]
   - [0x800006F0, "stack_init"]
   - [0x800006FC, "proc_700006FC"]
   - [0x80000718, "idle_entry"]
   - [0x80000738, "start_idle_thread"]
   - [0x80000790, "start_rmon_thread"]
   - [0x800007EC, "setup_message_queue_for_scheduler"]
   - [0x8000089C, "main_entry"]
   - [0x80000908, "setuplastentryofdebughandler"]
   - [0x80000970, "stderr.activated.set"]
   - [0x8000097C, "stderr.enable.set"]
   - [0x80000988, "stderr.permitted.set"]
   - [0x80000994, "user.Compare"]
   - [0x800009A0, "testtodisplaystderrandupdatecount"]
   - [0x800009F8, "testtodisplaystderrorevery16thframe"]
   - [0x80000A88, "storecurrentcountto800230a4"]
   - [0x80000AAC, "scheduler"]
   - [0x80000C70, "proc_70000C70"]